#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
# bspc monitor LVDS1 -d I II III IV V
# bspc monitor HDMI1 -d VI VII VIII IX X

bspc config split_ratio          0.50

bspc config focused_border_color "#7151E6"
bspc config normal_border_color "#2C1F59"
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 false

bspc config border_width        2
bspc config window_gap          8
bspc config top_padding 	28
bspc config bottom_padding 	2
bspc config top_monocle_padding 	-4
bspc config bottom_monocle_padding 	-3
bspc config focus_follows_pointer false
bspc config pointer_follows_focus true


# Screen Always On
#xset s off -dpms

# SpeedX
# xset r rate 250 45

# Wallpaper
feh --bg-scale ~/Pictures/wallpaper.jpg

# Polybar
polybar mybar &

# Picom
picom --experimental-backends &

# python
python ~/.config/bspwm/scripts/mpv_position.py &


# moc player
mocp -S
mocp -o repeat


bspc rule -a firefox desktop='^3' state=monocle follow=on border=off 
bspc rule -a "Org.gnome.Nautilus" state=floating
bspc rule -a mpv state=fullscreen 


